name: Run Postman and Commit HTML Report

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  postman-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Newman and HTML Reporter
        run: npm install -g newman newman-reporter-htmlextra --unsafe-perm=true

      - name: Run Postman Collection and Generate HTML Report in newman-report/
        run: |
          mkdir -p newman-report
          newman run tests/learningPOSTMAN.json \
            -r htmlextra \
            --reporter-htmlextra-export newman-report/report.html

      - name: Configure Git and Commit HTML Report
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          git add newman-report/report.html
          git commit -m "chore: update Postman HTML report [skip ci]" || echo "No changes to commit"
          git push