name: Run Postman and Upload HTML Report to Jira

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  postman-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Newman and HTML Reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Run Postman Collection (without environment)
        run: |
            mkdir -p newman
            newman run learningPOSTMAN.json \
              -r htmlextra \
              --reporter-htmlextra-export newman/report.html
        

      - name: Upload HTML Report to Jira
        run: |
          curl -D- \
            -u "${{ secrets.JIRA_USER_EMAIL }}:${{ secrets.JIRA_API_TOKEN }}" \
            -X POST \
            -H "X-Atlassian-Token: no-check" \
            -H "Content-Type: multipart/form-data" \
            -F "file=@newman/report.html" \
            https://${{ secrets.JIRA_DOMAIN }}/browse/${{ secrets.JIRA_ISSUE_KEY }}/attachments
