name: Run Postman and Upload HTML Report to Jira

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  postman-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Newman and HTML Reporter
        run: |
            npm install -g newman newman-reporter-htmlextra --unsafe-perm=true --allow-root
        
      - name: Run Postman Collection and Generate HTML Report
        run: |
            newman run learningPOSTMAN.json \
              -r htmlextra \
              --reporter-htmlextra-export ./report.html \
              || exit 1
        
      - name: Verify HTML report
        run: ls -l report.html
        