name: Run Postman and Upload to Xray

on:
  push:
    branches: [ main ]

jobs:
  newman-to-xray:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman and Save JSON Report
        run: |
          newman run learningPOSTMAN.json \
            -r json \
            --reporter-json-export result.json

      - name: Get Xray Token
        id: get_xray_token
        run: |
          RESPONSE=$(curl -s -X POST https://xray.cloud.getxray.app/api/v2/authenticate \
            -H "Content-Type: application/json" \
            -d '{"client_id": "${{ secrets.XRAY_CLIENT_ID }}", "client_secret": "${{ secrets.XRAY_CLIENT_SECRET }}"}')

          echo "token=$RESPONSE" >> $GITHUB_OUTPUT

      - name: Upload to Xray
        run: |
          curl -X POST https://xray.cloud.getxray.app/api/v2/import/execution/postman \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ steps.get_xray_token.outputs.token }}" \
            --data @result.json
