name: Postman Tests to Xray

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-postman-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Newman
        run: npm install -g newman newman-reporter-junit

      - name: Run Postman Collection
        run: |
          newman run tests/my_collection.json \
            -r junit --reporter-junit-export results.xml

      - name: Authenticate with Xray
        id: xray-auth
        run: |
          TOKEN=$(curl -s -H "Content-Type: application/json" \
            -X POST \
            -d '{
              "client_id": "${{ secrets.XRAY_CLIENT_ID }}",
              "client_secret": "${{ secrets.XRAY_CLIENT_SECRET }}"
            }' \
            https://xray.cloud.getxray.app/api/v2/authenticate | tr -d '"')
          echo "token=$TOKEN" >> $GITHUB_OUTPUT

      - name: Upload Results to Xray
        run: |
          curl -H "Content-Type: multipart/form-data" \
            -H "Authorization: Bearer ${{ steps.xray-auth.outputs.token }}" \
            -F "file=@results.xml" \
            "https://xray.cloud.getxray.app/api/v2/import/execution/junit?projectKey=MYK"