name: Run Postman Tests and Upload to Xray via xray-cli

on:
  workflow_dispatch:
    inputs:
      testExecutionKey:
        description: 'Jira Test Execution Key'
        required: true
        type: string

jobs:
  run-postman-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run Postman Tests in Docker (No Env File)
      run: |
        docker run --rm -v ${{ github.workspace }}:/etc/newman \
          postman/newman:alpine \
          run collection.json \
          --reporters cli,junit \
          --reporter-junit-export results.xml

    - name: Download and install xray-cli
      run: |
            curl -L https://github.com/Xray-App/xray-cli/releases/latest/download/xray-linux -o xray
            chmod +x xray
            sudo mv xray /usr/local/bin/xray
        

    - name: Upload Results to Xray using CLI
      run: |
        xray \
          --client-id "${{ secrets.XRAY_CLIENT_ID }}" \
          --client-secret "${{ secrets.XRAY_CLIENT_SECRET }}" \
          import junit \
          --testExecKey "${{ github.event.inputs.testExecutionKey }}" \
          --file results.xml
