name: Run Postman Tests and Upload to Xray

on:
  workflow_dispatch:
    inputs:
      testExecutionKey:
        description: 'Jira Test Execution Key'
        required: true
        type: string

jobs:
  run-postman-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Run Postman Tests in Docker (No Environment File)
      run: |
        docker run --rm -v ${{ github.workspace }}:/etc/newman \
          postman/newman:alpine \
          run learningPOSTMAN.json \
          --reporters cli,junit \
          --reporter-junit-export results.xml

    - name: Commit and push results.xml
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add results.xml
        git commit -m "Add results.xml from test run" || echo "No changes to commit"
        git push origin HEAD

    - name: Get Xray Auth Token
      id: get_token
      run: |
        response=$(curl -s -X POST https://xray.cloud.getxray.app/api/v2/authenticate \
          -H "Content-Type: application/json" \
          -d "{\"client_id\": \"${{ secrets.XRAY_CLIENT_ID }}\", \"client_secret\": \"${{ secrets.XRAY_CLIENT_SECRET }}\"}")
        echo "token=$response" >> $GITHUB_OUTPUT

    - name: Upload Results to Xray
      run: |
        curl -X POST "https://xray.cloud.getxray.app/api/v2/import/execution/junit?testExecKey=${{ github.event.inputs.testExecutionKey }}" \
          -H "Authorization: Bearer ${{ steps.get_token.outputs.token }}" \
          -F "file=@results.xml"
