name: Run Postman Tests and Upload to Xray

on:
  workflow_dispatch:
    inputs:
      testExecutionKey:
        description: 'Jira Test Execution Key (e.g. MYK-123)'
        required: true
        type: string

jobs:
  run-postman-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Run Postman tests with Newman and export JUnit XML
      run: |
        npm install -g newman
        newman run collection.json \
          --reporters cli,junit \
          --reporter-junit-export results.xml

    - name: Authenticate with Xray Cloud API
      id: auth
      run: |
        token=$(curl -s -X POST https://xray.cloud.getxray.app/api/v2/authenticate \
          -H "Content-Type: application/json" \
          -d "{\"client_id\": \"${{ secrets.XRAY_CLIENT_ID }}\", \"client_secret\": \"${{ secrets.XRAY_CLIENT_SECRET }}\"}" | tr -d '"')
        echo "token=$token" >> $GITHUB_OUTPUT

    - name: Upload JUnit results to Xray
      run: |
        curl -X POST "https://xray.cloud.getxray.app/api/v2/import/execution/junit?testExecKey=${{ github.event.inputs.testExecutionKey }}" \
          -H "Authorization: Bearer ${{ steps.auth.outputs.token }}" \
          -F "file=@results.xml"
