name: Run Postman and Upload to Xray with Test Execution Link

on:
  push:
    branches: [main]

jobs:
  upload-to-xray:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman and generate JSON report
        run: |
          newman run learningPOSTMAN.json \
            -r json \
            --reporter-json-export result.json

      - name: Get Xray API token
        id: get_xray_token
        run: |
          RESPONSE=$(curl -s -X POST https://xray.cloud.getxray.app/api/v2/authenticate \
            -H "Content-Type: application/json" \
            -d '{"client_id": "${{ secrets.XRAY_CLIENT_ID }}", "client_secret": "${{ secrets.XRAY_CLIENT_SECRET }}"}')
          echo "token=$RESPONSE" >> $GITHUB_OUTPUT

      - name: Upload Newman JSON to Xray with Test Execution key
        run: |
          curl -X POST "https://xray.cloud.getxray.app/api/v2/import/execution/postman?testExecKey=${{ secrets.XRAY_TEST_EXECUTION_KEY }}" \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ steps.get_xray_token.outputs.token }}" \
            --data @result.json
