name: Run Postman and Upload HTML Report to Jira

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  postman-to-jira:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Newman and HTML Reporter
        run: npm install -g newman newman-reporter-htmlextra --unsafe-perm=true

      - name: Run Postman Collection and Generate HTML Report
        run: |
          newman run learningPOSTMAN.json \
            -r htmlextra \
            --reporter-htmlextra-export report.html

      - name: Upload HTML Report to Jira
        env:
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_DOMAIN: ${{ secrets.JIRA_DOMAIN }}
          JIRA_ISSUE_KEY: ${{ secrets.JIRA_ISSUE_KEY }}
        run: |
          curl -D- \
            -u "$JIRA_USER_EMAIL:$JIRA_API_TOKEN" \
            -X POST \
            -H "X-Atlassian-Token: no-check" \
            -H "Content-Type: multipart/form-data" \
            -F "file=@report.html" \
            "https://${JIRA_DOMAIN}/rest/api/3/issue/${JIRA_ISSUE_KEY}/attachments"
